apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulutbilisim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulutbilisim
  template:
    metadata:
      labels:
        app: bulutbilisim
    spec:
      containers:
      - name: bulutbilisim-kub
        image: furkansaglams/bulutbilisimdockerhub:v9
        ports:
        - containerPort: 8080