apiVersion: apps/v7
kind: Deployment
metadata:
  name: bulut-bilisim-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulut-bilisim-project
  template:
    metadata:
      labels:
        app: bulut-bilisim-project
    spec:
      containers:
      - name: bulut-bilisim-project-kub
        image: furkansaglams/bulutbilisimdockerhub:v7
        ports:
        - containerPort: 8080