apiVersion: v1
kind: Service
metadata:
  name: bulutbilisimservice
spec:
  selector:
    name: bulutbilisimservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer