apiVersion: v1
kind: Service
metadata:
  name: bulut-bilisim-project-service
spec:
  selector:
    app: bulut-bilisim-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer